// Code generated by running "go generate" by utility db2struct: "https://github.com/webnice/d2s"; DO NOT EDIT.
// This file was generated at 18.03.2019 11:43:57 UTC
// Generator: db2struct (go get -u gopkg.in/webnice/d2s.v1/db2struct)

// The structure is based on the database table structure.
// Database: "sample"
// Table: "goose_db_version"

package goose // import "application/models/goose"

import (
	nul "gopkg.in/webnice/lin.v1/nl"
)

// DbVersion 
type DbVersion struct {
	ID        uint64   `db:"id"         gorm:"column:id;primary_key;        AUTO_INCREMENT;NOT NULL;DEFAULT NULL;precision:20;type:BIGINT(20) UNSIGNED"` // Лог миграций проекта
	VersionID int64    `db:"version_id" gorm:"column:version_id;            NOT NULL;DEFAULT NULL;precision:19;type:BIGINT(20)"                        ` // 
	IsApplied bool     `db:"is_applied" gorm:"column:is_applied;            NOT NULL;DEFAULT NULL;type:TINYINT(1)"                                     ` // 
	Tstamp    nul.Time `db:"tstamp"     gorm:"column:tstamp;                NULL;DEFAULT 'CURRENT_TIMESTAMP';type:TIMESTAMP"                           ` // 
}
