// Code generated by running "go generate" by utility db2struct: "https://github.com/webnice/d2s"; DO NOT EDIT.
// This file was generated at 18.03.2019 11:43:57 UTC
// Generator: db2struct (go get -u gopkg.in/webnice/d2s.v1/db2struct)

// The structure is based on the database table structure.
// Database: "sample"
// Table: "filestore"

package types // import "application/models/filestore/types"

import (
	nul "gopkg.in/webnice/lin.v1/nl"
)

// Filestore Реестр файлов постоянного хранения
type Filestore struct {
	ID          uint64     `db:"id"          gorm:"column:id;primary_key;         AUTO_INCREMENT;NOT NULL;DEFAULT NULL;precision:20;type:BIGINT(20) UNSIGNED"` // Уникальный идентификатор записи
	CreateAt    nul.Time   `db:"createAt"    gorm:"column:createAt;               NULL;DEFAULT NULL;type:DATETIME"                                           ` // Дата и время создания записи
	UpdateAt    nul.Time   `db:"updateAt"    gorm:"column:updateAt;               NULL;DEFAULT NULL;type:DATETIME"                                           ` // Дата и время обновления записи
	DeleteAt    nul.Time   `db:"deleteAt"    gorm:"column:deleteAt;               NULL;DEFAULT NULL;type:DATETIME"                                           ` // Дата и время удаления записи (пометка на удаление)
	AccessAt    nul.Time   `db:"accessAt"    gorm:"column:accessAt;               NULL;DEFAULT NULL;type:DATETIME"                                           ` // Дата и время последнего доступа к записи
	Filename    nul.String `db:"filename"    gorm:"column:filename;               NULL;DEFAULT NULL;size:4096;type:VARCHAR(4096)"                            ` // Оригинальное имя файла
	FileExt     nul.String `db:"fileExt"     gorm:"column:fileExt;                NULL;DEFAULT NULL;size:256;type:VARCHAR(256)"                              ` // Расширение имени файла без точки
	Size        uint64     `db:"size"        gorm:"column:size;                   NOT NULL;DEFAULT '0';precision:20;type:BIGINT(20) UNSIGNED"                ` // Размер файла в байтах
	Sha512      nul.String `db:"sha512"      gorm:"column:sha512;                 NULL;DEFAULT NULL;size:128;type:VARCHAR(128)"                              ` // SHA512 контрольная сумма файла в HEX формате
	LocalPath   nul.String `db:"localPath"   gorm:"column:localPath;              NULL;DEFAULT NULL;size:4096;type:VARCHAR(4096)"                            ` // Относительный путь и имя файла
	ContentType nul.String `db:"contentType" gorm:"column:contentType;            NULL;DEFAULT NULL;size:65535;type:TEXT"                                    ` // MIME Content-Type загруженного файла
}
